### ISSUE TITLE
Installer for MS vs2013

### ISSUE THREAD

**Issue by jacobmesu** [ComponentFactory/Krypton#1]
- Generated documentation
- Automatically adding items to the toolbox

**Comment by ComponentFactory** [comment]
I have added Help\KryptonHelp.cab which is a file containing the .mshc file that is installed as part of the installer to add help. It installed to work with the Microsoft Help Viewer that was the new way of handling help files from Visual Studio 2010 onwards.

**Comment by ComponentFactory** [comment]
Just added the source for the Visual Studio installer projects inside the Installer directory. I think only the Suite Source one and the MM ones are relevant. The others were used when I sold separate installs for individual components.

**Comment by jacobmesu** [comment]
Thanks! Unfortunately Visual Studio 2013 no longer supports this projecttype. Recommended alternative is the Wix toolset. So I think I'm going to replace this projects with the Wix solution. On a side note, how did you add the items to the toolbox? I used a seperate exe which creates a visual studio COM object. Then the exe creates a temporary winforms project and I manually add the items to the toolbox. But this solution is prone to error.

**Comment by jacobmesu** [comment]
For reference purpose: http://sourceforge.net/p/guifreaks/code/HEAD/tree/NaviSuite2/Src/Guifreaks.ToolboxInstaller/ToolboxItemsInstaller.cs
