### ISSUE TITLE
What is the font used in the kryptonlabel control ?

### ISSUE THREAD

**Issue by omarrrio** [ComponentFactory/Krypton#104]
What is the  name of the control used in the kryptonlabel please ? i am trying to change the size of the font but i have to pick an entire new font.

**Comment by Smurf-IV** [comment]
Can be done in the designer....

**Comment by Threetwosevensixseven** [comment]
The default font varies between Calibri and Tahoma at runtime, depending on
the OS.

I used to copy the existing font and clone it with a new size in the
runtime setup code.

**Comment by omarrrio** [comment]
Thank you, i'll just use that
