### ISSUE TITLE
Custom palettes

### ISSUE THREAD

**Issue by Wagnerp** [ComponentFactory/Krypton#122]
How do we load user created palette files that were exported from the `Palette Designer` into our own applications?

**Comment by phlexss** [comment]
I'm very eager to get an answer to this too......

**Comment by phlexss** [comment]
Just found out myself....it's so simple;

- add a KryptonManager and KryptonPalette to the form
- set "GlobalPalette" of KryptonManager to "KryptonPalette1"
- in your code import the palette xml-file using KryptonPalette1.Import

et voila.

**Comment by Wagnerp** [comment]
@phlexss 

Yes, easy as that.
