### ISSUE TITLE
Can't compile in visual studio 2013/2017 Community

### ISSUE THREAD

**Issue by bhubanstha** [ComponentFactory/Krypton#143]
As of 19th July 2018 I can't compile krypton components.  I opened krypton source code by using Krypton Components Suite 2015.sln which is inside source/krypton components when i try to compile i get dll not found errors.

**Comment by megakraken** [comment]
Yes some people broke the solution with their _improvements_ and then never cared to fix it. Just checkout the [last commit](https://github.com/ComponentFactory/Krypton/tree/5db2ec99aa98657100887324760a5db7996728a2) from the original author, that one still works fine.

**Comment by Wagnerp** [comment]
@bhubanstha and @megakraken 

I'll look into it today, if I recall I had this problem back in December 2017. So it may require a code reset. If that is the case, then I'll ensure that the fix for #79 is included. By the way, it won't work for VS 2013, as it is a 2015 solution file.

**Comment by Wagnerp** [comment]
@bhubanstha 

I have pushed a pull request to this repo to unwind it back to Jan 2017. I have got a repo for [.NET 4](https://github.com/Wagnerp/Krypton-NET-4.00), which does away with the designer DLL.
