### ISSUE TITLE
Issue Reading Documentation 

### ISSUE THREAD

**Issue by robertjawoods** [ComponentFactory/Krypton#17]
After creating a manifest for the help files using [MSHC Migrate](http://mshcmigrate.helpmvp.com/home) and loading it into Microsoft Help Viewer, I get an error and a blank page except for the page title.

![image](https://cloud.githubusercontent.com/assets/19418761/21937176/1b92b3b0-d9ae-11e6-8d3b-7248148c67b7.png)

![image](https://cloud.githubusercontent.com/assets/19418761/21937203/426fc248-d9ae-11e6-9bef-1df2f29415b5.png)

[msha.zip](https://github.com/ComponentFactory/Krypton/files/704799/msha.zip)

**Comment by Cocotteseb** [comment]
I've done some work on my fork (I should do a pull request) This the best I've managed to do.Hope this helps! https://github.com/Cocotteseb/Krypton/issues/2

**Comment by ComponentFactory** [comment]
I have now uploaded a .chm help file that allows you to get started with documentation. It is in the /Help directory.
