### ISSUE TITLE
Toggle Button

### ISSUE THREAD

**Issue by DrewLittler** [ComponentFactory/Krypton#177]
Does anyone know how I can create a toggle button using a Krypton component? 

Using raw winforms components, I'd use a CheckBox and set the appearance to "button". But I can't find anything like that on KryptonCheckBox. I've also had a look at the properties of KryptonButton to see if there's any support for making that work like a toggle button, but I couldn't spot anything there.

Cheers!

**Comment by Wagnerp** [comment]
Hi @DrewLittler 

I've actually created one in [this project](https://github.com/Wagnerp/Krypton-Toolkit-Suite-Extended-NET-5.470)

**Comment by mace17** [comment]
Hi, try to use KryptonCheckButton

**Comment by DrewLittler** [comment]
KryptonCheckButton! I totally didn't spot that! But I'll also look at the toggle switch too!
