### ISSUE TITLE
Design time bug

### ISSUE THREAD

**Issue by Wagnerp** [ComponentFactory/Krypton#18]
Identified bug whereby controls do not appear on the form, instead they appear on the area where the timer, background worker, dialog controls appear. Did try gacutil with no success. See screenshot attached for visual detail.

![krypton bug](https://cloud.githubusercontent.com/assets/949607/22032384/275a67f2-dcdc-11e6-8624-35d85dea7907.PNG)

Did have a deep look at the source code for the toolkit, but couldn't find anything glaring at me.

**Comment by mbagattini** [comment]
I had the same problem, check if you have more than one version of the same
assembly registered in the GAC; my suggestion is to deregister everything
krypton related then register the appropriate dlls


Il giorno mar 17 gen 2017 alle 18:41 Wagnerp <notifications@github.com> ha
scritto:

**Comment by Cocotteseb** [comment]
Hi 
For design time support you need to register the *.design.dll (and reboot computer believe me !). Sometimes you need to make another project to see changes.

**Comment by Wagnerp** [comment]
Hi @mbagattini and @Cocotteseb 

Many thanks for your input, I did try registering the assemblies using GAC and rebooting my computer, but this didn't solve the issue for me. Is there a way I can clear the cache to try again?

**Comment by mbagattini** [comment]
What do you see when, from elevated developer command prompt, you run
gacutil -l componentfactory.krypton.design?

**Comment by Wagnerp** [comment]
Hi @mbagattini 

It did work, but it needed a full shutdown not a reboot. I left it overnight, powered it back up this morning and it now works. Not quite sure of the logic of that!

**Comment by mbagattini** [comment]
Glad to hear that. Maybe it needed some rest :)
