### ISSUE TITLE
Can't install onto tool palette - vs 2019

### ISSUE THREAD

**Issue by pixelinkmedia** [ComponentFactory/Krypton#192]
I have VS 2019
I get this error when trying to browse/install the dll's into the toolbox
![krypton](https://user-images.githubusercontent.com/51757955/67201430-4bb0b900-f3d4-11e9-89fe-5e82a744069f.jpg)

**Comment by Wagnerp** [comment]
Hi @pixelinkmedia 

It looks like that you're using a very old version of the toolkit. What .NET version are you using, so that I can direct you to the right NuGet packages to install?

**Comment by pixelinkmedia** [comment]
I am Using VS 2019
.NET 4.7.2

**Comment by Wagnerp** [comment]
Hi @pixelinkmedia 

If you look at this page, and add these NuGet packages to your project, it'll solve the problem for you.

**Comment by pixelinkmedia** [comment]
Look at what page?

**Comment by Wagnerp** [comment]
@pixelinkmedia 

Sorry, I forgot to add this [link](https://github.com/Wagnerp/Krypton-NET-Version-Dashboard/blob/master/Documents/Modules/Standard/Krypton-Toolkit-Suite-Standard-5472-Modules.md)

**Comment by pixelinkmedia** [comment]
Well, got it hooked up to Nuget, but after closing the NuGet Manager window, it tries to load the package, but it just hangs saying "loading..." Stayed like that fro 45 minutes. However, it is already in the online version, inside NuGet anyways,... installed that fine

**Comment by pixelinkmedia** [comment]
I downloaded the Examples, but they are only EXE's. Do you have VB source examples. ?

**Comment by pixelinkmedia** [comment]
Never, mind, I found the code example

**Comment by pixelinkmedia** [comment]
I found the example code, but it require .NET 4.7 and would not work. Designer errors galore.

Do you have 4.7.2 Examples?

**Comment by pixelinkmedia** [comment]
I found the example code, but it require .NET 4.7 and would not work. Designer errors galore.
Do you have 4.7.2 Examples?

or do you have an online help with example VB syntax.
I am really interested in on how to skin (or Patelette) designer works

**Comment by Wagnerp** [comment]
The examples are only available in C#, since all new versions are a port of the original 4.4.0 version. If you're interested in using custom palettes, I've provided a VB snippet [here](https://wagnerp.github.io/Krypton-NET-5.470/Help/Output/articles/palettes.html)

**Comment by Wagnerp** [comment]
Though, I could convert the C# examples over to VB while preserving the C# examples!

**Comment by pixelinkmedia** [comment]
Hi,
I after getting the install to work.
If I create a new project all the Controls have disappeared from the toolbox.
How come?

**Comment by Wagnerp** [comment]
Its because you need to install the NuGet packages into every project that you create. The binaries are not installed to your machine like a normal piece of software.

**Comment by djsnts** [comment]
pixelinkmedia did you or anyone else figure out how to get the controls in toolbox in Visual Studio. I am using Visual Studio 2017 Enterprise.

I would really like to have these controls in my Visual Studio toolbox.
Thanks.

**Comment by pixelinkmedia** [comment]
Yes, as per instructions from Wagnerp, you need to install the Nugent packages into every project. Then the components will be loaded into the toolbox for that particular project

**Comment by djsnts** [comment]
Wow. I found a way and it stays in your toolbox. Download the NuGet package (kryptonsuite47b.4.7.0.nupkg) and install from the command prompt as instructed on NuGet.

After that open or create a new project. Open your toolbox in Visual Studio, right click on the toolbox and add a tab. Find your krypton dll's (should be 6) and copy them and then right click and paste them into the krypton tab in the toolbox.

Save your project and exit VS. The controls should now be in your krypton tab every time you open or create a new project in VS. It is for me at least. Have both Visual Studio 2017 & 2019 Enterprise.
