### ISSUE TITLE
Cause an exception "ReadOnly controls collection" - when adding new button

### ISSUE THREAD

**Issue by aznflipmode** [ComponentFactory/Krypton#193]
I've taken over someone else's project and they have used Krypton.  I tried to add a button on a toolbar.  I also tried adding a new menu item but both times,  i get this error:

this.kryptonHeaderGroupMain.Controls.Add(this.kryptonHeaderGroupMain.Panel);

and it mucks up the Designer View.

FYI:  I have tried "other" suggestions such as changing it to:
this.<kryptonControlsContainer>.Panel.Controls.Add(this.<otherControlName>);

.. but I would get "A circular control reference has been made. A control cannot be owned by or  parented to itself." error

What am i missing?  Thanks!

**Comment by aznflipmode** [comment]
just FYI.  Any changes I make on the UI will give me that error - "ReadOnly controls collection"

**Comment by Wagnerp** [comment]
Where did you find the original project?

**Comment by aznflipmode** [comment]
Work

**Comment by Wagnerp** [comment]
[This](https://www.codeproject.com/questions/359649/how-to-solve-a-circular-control-reference-has-been) may help

**Comment by aznflipmode** [comment]
Also, just to add.. the project was built on version Version=3.0.8.0 - it that makes any difference

**Comment by Wagnerp** [comment]
Newer versions does have newer features, I can't remember what version 3.x came with. It was so long ago.

**Comment by Wagnerp** [comment]
In the newer 5.472 port, you do have high DPI support.

**Comment by aznflipmode** [comment]
Thanks for looking into it, looks like it was the design.dll .. 1) it needed to be added.  2) Save the project and restart it. 3) Now i can edit the UI

**Comment by Wagnerp** [comment]
It's good to see that it works, though I would recommend upgrading, as newer versions don't require the Design.dll to work. Plus newer versions are actively supported.
