### ISSUE TITLE
Image is not displayed on KryptonButton

### ISSUE THREAD

**Issue by admin-pcngroup** [ComponentFactory/Krypton#205]
Hello everyone,
I use Visual Studio 2019 on Win 10 and I'm developing in VB.Net.
I set an Image (32px x 32 px) under Values in a KryptonButton. The image is correctly displayed on the editor but when I debug, it is not displayed at all. What can I do?
Thank you all

![image](https://user-images.githubusercontent.com/48631855/78989251-69650c80-7b33-11ea-9932-580f7ffbf4de.png)
_On editor_

![image](https://user-images.githubusercontent.com/48631855/78989286-80a3fa00-7b33-11ea-85df-80579028ab94.png)
_While debugging_

**Comment by Wagnerp** [comment]
Hi @admin-pcngroup 

Have you added the image to your projects' resources file?

**Comment by admin-pcngroup** [comment]
Hello, yes, of course. I can view them also when I type ```My.Resources. ...``` thank to IntelliSense. Thank you for your answer(s). Sent from my Huawei phone-------- Original message --------From: Peter Wagner <notifications@github.com>Date: Fri, 17 Apr 2020, 19:21To: ComponentFactory/Krypton <Krypton@noreply.github.com>Cc: admin-pcngroup <administrator@pcngroup.ch>, Mention <mention@noreply.github.com>Subject: Re: [ComponentFactory/Krypton] Image is not displayed on KryptonButton (#205)
Hi @admin-pcngroup
Have you added the image to your projects' resources file?

**Comment by admin-pcngroup** [comment]
Hello, yes, of course. I can view them also when I type `My.Resources. ...` thank to IntelliSense. Thank you for your answer(s).

**Comment by Wagnerp** [comment]
@admin-pcngroup Is it working now?

**Comment by admin-pcngroup** [comment]
Unfortunately, it isn't

**Comment by Wagnerp** [comment]
@admin-pcngroup You may want to try to make the button bigger. I think it's seeing it as a 16 x 16 image, or resize the image.

**Comment by admin-pcngroup** [comment]
Thank you. I've tried both. It works like a charm!!

**Comment by Wagnerp** [comment]
@admin-pcngroup Glad to help!
