### ISSUE TITLE
How to change font

### ISSUE THREAD

**Issue by joeyseisma** [ComponentFactory/Krypton#206]
Hi,

Thank you very much for this very nice package. 

Sounds seemingly simple, but I cannot change the font of the DateTimePicker, ComboBox, Label.

I would set a new value in Font property, but it's still is displayed using the DefaultFont. However, if I query the Font property, it returns the new font I set.

TIA!

**Comment by lukeattard** [comment]
What is the code that you are using?

**Comment by joeyseisma** [comment]
Hi,

startTime is the dt picker.

``
def var newFont as System.Drawing.Font.
newFont = new System.Drawing.Font("Microsoft Sans Serif", Progress.Util.CastUtil:ToSingle(18), System.Drawing.FontStyle:Bold, System.Drawing.GraphicsUnit:Point, System.Convert:ToByte(0)).

this-object:startTime:Font = newFont.

``

Thx!

**Comment by joeyseisma** [comment]
![Krypton](https://user-images.githubusercontent.com/60824527/80041193-a4aaf800-84b0-11ea-9934-584e38d569b2.jpg)

**Comment by RPG64** [comment]
Hi Joey,
look at the different states the controls offer and try to modify at least StateCommon like
`kryptonControl.StateCommon.Content.Font = New System.Drawing.Font("Elephant", 15.75!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))`

**Comment by joeyseisma** [comment]
Oh I see. It's a little deep, I thought went through each of the properties many times. :-)

Big Thanks!

**Comment by RPG64** [comment]
Glad to help :-)
