### ISSUE TITLE
How do you change the font of list items in combobox

### ISSUE THREAD

**Issue by joeyseisma** [ComponentFactory/Krypton#208]
Hi,

Changed the font in StateCommon -> ComboBox -> Content -> Font

But that don't change the font when you click the drop down button. 

How to make the list items font the same?

Thanks!

**Comment by joeyseisma** [comment]
StateCommon.Item.Content.ShortText.Font

**Comment by John11Dave** [comment]
If I change this why is the text gone? but when I select on it, it displays on the combobox

**Comment by John11Dave** [comment]
If the size is greater than 10 the text is just gone, and if padding is greater than -1 the text is also gone. please help
