### ISSUE TITLE
"OutOfMemoryException" will be threw if click a button to show KryptonForm many times 

### ISSUE THREAD

**Issue by imszy** [ComponentFactory/Krypton#223]
Click a button to show another KryptonForm that have many KryptonTextbox controls (about 50 controls).
Click the button, then close the form many times. 
The memory keeps increasing and it will throw OutOfMemoryException after 10minutes.

Anyone knows how to fix it?

**Comment by Smurf-IV** [comment]
The recommended practice for forms is to:
wrap your form creation in a using. 

i.e.

``` c#
            using (var startAndCheck = serviceProvider.GetRequiredService<CheckForNewerVersion>())
            {
                startAndCheck.ShowInTaskbar = true;
                if (startAndCheck.ShowDialog() != DialogResult.OK)
                {
                    Add(@"Exiting");
                    return;
                }
            }
```

**Comment by imszy** [comment]
It works. 
Thank you so much! @Smurf-IV

**Comment by imszy** [comment]
Thanks @Smurf-IV response!
His solution is effective.

**Comment by Smurf-IV** [comment]
Great - Please close this issue then ;-)

**Comment by imszy** [comment]
Oh, yes. Thank you!

**Comment by imszy** [comment]
Oh, yes. Thank you.

**Comment by imszy** [comment]
Thank you.

**Comment by imszy** [comment]
Oh, yes. Thank you!
