### ISSUE TITLE
The components are not appearing in toolbox 

### ISSUE THREAD

**Issue by amjadfqs** [ComponentFactory/Krypton#225]
I'm using **VS2015**, after I choose the dll files It appears to load then it show NOTHING.

**Comment by zhienjbigs** [comment]
same with vs2019

**Comment by amjadfqs** [comment]
@zhienjbigs 

I solved my problem by dragging the dll Files into the tab in the toolbox directly, I didn't choose item, dragged them directly.

**Comment by ThiagoMoura183** [comment]
Thanks! It was useful!
