### ISSUE TITLE
Change Font style and size of Buttons

### ISSUE THREAD

**Issue by shami81** [ComponentFactory/Krypton#228]
Hello there,
First of all a bundle of thanks for sharing your UI components as an open source and free to use package. Kindly tell me how can I change the font style and font size of the Buttons specially and other controls as well? Currently it is not visible in the properties windows I can only change the text string.

**Comment by Smurf-IV** [comment]
Each "Krypton" element has at least the following "State"s
![image](https://user-images.githubusercontent.com/2418812/147847247-f5ce0325-a530-473f-ab42-c1882b51493b.png)

The easiest is to change the "StateCommon" as this will apply to all states then:
![image](https://user-images.githubusercontent.com/2418812/147847265-88d5ffc6-9c19-4e5f-b8e8-c8b115ffbc0d.png)

If you want to do it at a the global level then someone else can answer that (As I have found that to be most perplexing for accurate control)

**Comment by shami81** [comment]
@Smurf-IV Thanks a lot Sir for the help. Really appreciate that.
