### ISSUE TITLE
KryptonLabel TextAlign property

### ISSUE THREAD

**Issue by iltan987** [ComponentFactory/Krypton#240]
I couldn't find anything related to Text Align property. How can I set Text Align?

**Comment by Wagnerp** [comment]
Hi @iltan987 

It's under `StateCommon` > `ShortText` > `TextH/V`

**Comment by iltan987** [comment]
> Hi @iltan987
> 
> It's under `StateCommon` > `ShortText` > `TextH/V`

Thanks a lot
