### ISSUE TITLE
Krypton Navigator - outlook full Nav Mode

### ISSUE THREAD

**Issue by almendieta** [ComponentFactory/Krypton#253]
When you try to place krypton navigator in VS IDE, it crashes Visual Studio 2022. Krypton Navigator version: 80.23.11.231. 70 version is working correctly, but get back to it it's a REAL nightmare.
![2023-12-20 12_23_41-Window](https://github.com/ComponentFactory/Krypton/assets/11827218/2bdc544d-9af3-4fc4-a5ca-7016e1594165)

**Comment by Smurf-IV** [comment]
@almendieta 
Component factory does not go above V 4.5
Please delete this and move it to the Krpyton-suite github project

**Comment by almendieta** [comment]
Thanks for the answer, I've just move it to Krypton Suite GH project. I can not delete this message, couldn't find a way to do it.
