### ISSUE TITLE
Facing issue in drag drop controls on form

### ISSUE THREAD

**Issue by arpit-nagar** [ComponentFactory/Krypton#3]
Hi @ComponentFactory 
Thanks for making this code open source. I liked this code very much.

@ComponentFactory, @jacobmesu,
I am trying to use this code in visual studio 2015 
but I am not able to drag-drop any krypton control on Form.
May be I am missing some steps with Installer.
Can you please help me to solve this issue.

Thanks

**Comment by pedrohex** [comment]
Hi,
Iam having this issue too. Is somehow related with license. I was wondering if the author could disable this checks. Thank you

**Comment by pedrohex** [comment]
Is already open as issue #2 . Great

**Comment by jacobmesu** [comment]
I'll have a separate branch (2013) which fixes all this issues and with a new installer. I'll soon push it to the master.

**Comment by pedrohex** [comment]
Thank you Jacob

**Comment by arpit-nagar** [comment]
@jacobmesu,
I tried with branch 2013...but no luck :-1:

**Comment by arpit-nagar** [comment]
I think VS 2015 installation steps are missing.
Also for me bin folder should not be a part of code and msi Installer should have to be a release artifact.

**Comment by arpit-nagar** [comment]
Hi @ComponentFactory, @jacobmesu 
Can you please tell... why we need a installer. 
Can we do work without installing via installer.

As per as I see... I only found installer is used to register dll in GAC.
Can we write a batch script and do the same?
Please correct me if I am wrong.

**Comment by Cocotteseb** [comment]
Hello,

For design time (drag and drop components) you need to register in the GAC the design dlls (contained in the project design), and reboot your computer (be sure to do it even if you don't believe me!)
You can just call the gacutil utility when you compiles. 
Take a look to the fork I've made of the Krypton suite here. 
(    <PostBuildEvent>"$(ProjectDir)..\GacUtil.exe" -i "$(TargetPath)" /f</PostBuildEvent>)

The installer installs the dlls in the GAC and register the components in the toolbox but you can do yourself with "choose elements" in the toolbox with right click.

**Comment by pedrohex** [comment]
Cocotteseb, 
I had already done that but still with license issues. I've tried register manually all the dlls (dev or publisher signed) and no luck. I can design with windows forms designer but i allways get a license error. The source code doesn't have the licensing module. 
There's an open issue #2 to remove this , lets hope the editor does it.

**Comment by Cocotteseb** [comment]
In my fork I have removed all the licensing code. Be sure you have no *.licx file in your solution left. If yes please delete them, that's causing trouble.

**Comment by pedrohex** [comment]
Thank you, ill check it. Nice job with the OutlookGrid by the way, ill check it too ;)

**Comment by arpit-nagar** [comment]
Thanks @Cocotteseb and @jacobmesu  for your quick inputs.
@Cocotteseb nice work with Office 2013 theme. I liked it :+1: 
Can you please send a MR request with a working/clean copy. It will be much useful.

**Comment by jacobmesu** [comment]
My installer does nothing fancy. Adding the assemblies to the Gac and it creates a new registry key which loads the compoments in the toolbox when launching visual studio. You can do that with a script as well.

**Comment by markrivo** [comment]
Hi, It works for me,
I first download the latest wixtoolset found in [http://wixtoolset.org/releases/] so i can open it in VS 2013
Next I add the path of where the gacutil.exe to the PATH environment variable.
Lastly, I rebuild the solution and I got the Krypton.Installer and install it on my workstation

**Comment by Mag999** [comment]
Hello,
I try to get the krypton tools running in Visual Studio 2013 but without success. Is an pre-compiled installation package available for the components? I also tried to compile the installer but get so much errors because of wrong path of the components.
When I drag and drop the DLL in the Toolbox, the Krypton Components will be diplayed, but cannot bring them on the form.
Any help is highly appreciated.
if anybody knows how to fix it you can also mail me directly at marcokroe@gmx.de

Thanks a lot.

**Comment by calet84** [comment]
help to resolve the error drag and drop controls and dlls are already registered please help thanks

**Comment by tanffn** [comment]
Thank you @Cocotteseb and @jacobmesu for the input and the brunch.
I compiled (registered) and installed the components, but now the ComboBox component gives me an error (which it didn't before).

_Opening the sample:_
Source\Krypton Toolkit Examples\KryptonComboBox Examples

_Will give the following error:_
Unable to find am entry point named SelectClipRgnInvoke in DLL gdi32.dll

_Source In:_ 
ComponentFactory.Krypton.Toolkit\General\PlatformInvoke.cs

```
        [SecurityCritical]
        [DllImport("gdi32.dll", CharSet = CharSet.Auto, SetLastError = true, ExactSpelling = true)]
        private static extern int SelectClipRgnInvoke(IntPtr hDC, IntPtr hRgn);

        [SecuritySafeCritical]
        internal static int SelectClipRgn(IntPtr hDC, IntPtr hRgn)
        {
            return SelectClipRgnInvoke(hDC, hRgn);
        }
```

**Comment by tanffn** [comment]
I returned it to the original code, which works.

I don't understand why the change from SelectClipRgn to SelectClipRgnInvoke and added the wrapper :/

```
        [DllImport("gdi32.dll", CharSet = CharSet.Auto, SetLastError = true, ExactSpelling = true)]
        internal static extern int SelectClipRgn(HandleRef hDC, HandleRef hRgn);

        [DllImport("gdi32.dll", CharSet = CharSet.Auto, SetLastError = true, ExactSpelling = true)]
        internal static extern int SelectClipRgn(IntPtr hDC, IntPtr hRgn);
```

**Comment by yp25** [comment]
@ComponentFactory Thanks for sharing your great work.  
@jacobmesu  Thanks for sharing the 2013 branch which running flawlessly in my environment
 @Cocotteseb Thanks for pointing about GAC and removing the license. I learn something from GAC. And about the original license code, in my opinion @ComponentFactory  implement good enough protection. I think somebody must learn from it. 
@tanffn Thanks for pointing the original code PlatformInvoke.cs it help me solve my problem too.

**Comment by arpit-nagar** [comment]
@ComponentFactory we can also close this issue.
It will be great, if you can provide a installer in release.

**Comment by pc8181** [comment]
same error i have faced

![image](https://cloud.githubusercontent.com/assets/13380400/26276181/06a6275c-3d27-11e7-99c7-2938ee3d3ab5.png)
