### ISSUE TITLE
Using KryptonForm

### ISSUE THREAD

**Issue by epje** [ComponentFactory/Krypton#34]
Hello there,

I'm having a little difficulty with my Krypton installation.

I've managed to install the Krypton Components into the GAC as per the instructions - the controls all work as expected, no problems there. I remember the old Krypton installer put a Krypton Form template into the New Project dialog, but this obviously doesn't happen now.

How would I go about changing the default form style from the Windows look to the Krypton look? I'd like my project to look uniform, and having the default Windows style ruins the effect for obvious reasons!

I understand from the help file that one must inherit from _KryptonForm_ as opposed to _Form_. I see from other Krypton projects I have found that the **MainForm** is found in **ComponentFactory.Krypton.Toolkit.KryptonForm**, but I just can't work out how to load it!

Any help with this would be much appreciated - it is highly frustrating!

Kind regards,
~Ed

**Comment by Wagnerp** [comment]
Hi @epje 

If you want to 'convert' a standard form into a KryptonForm, go to the code view and in your declarations simply put `using ComponentFactory.Krypton.ToolKit;` then replace Form after the : with KryptonForm.

Hope this helps!

**Comment by epje** [comment]
Hi @Wagnerp 

That worked like a charm! Thanks very much.

~Ed

**Comment by crisbr002** [comment]
Hello, I'm not getting it to work. Could you help me with a step by step?

I have done the procedures that said but Form does not work.

If possible, with printscreen would help me a lot.

Please help me.

Thank you

**Comment by crisbr002** [comment]
I've already done these steps here:
# Using with Visual Studio #
 - Run the batch file **RegisterToGAC.bat** in the **Bin** directory as an admin so the assemblies are placed in the GAC
 - Start **Visual Studio** and create/open your Windows Forms project
 - Open the main Form of your application and show the **Toolbox**
 - Right click the **Toolbox** and **Add Tab**, give it the name **Krypton**
 - Right click inside the new tab and select **Choose Toolbox Items**
 - Use the **Browse** button and go to your **Bin** directory, select all the **ComponentFactory.Krypton...** assemblies
 - Ignore warning for **ComponentFactory.Krypton.Design.dll** as it does not have any controls in it
 - Select **OK** and now you have them all in the **Toolbox!**

I'm having trouble making Form work.

**Comment by Wagnerp** [comment]
Hi @crisbr002 

Can you please confirm if all of the controls work as per usual before stepping through the instructions I gave above?

**Comment by almendieta** [comment]
Hello, here is how you can get working Krypton at design time:

1. Create a tab named Krypton (as explained in README) and add:

ComponentFactory.Krypton.Toolkit.dll

(from ...\Krypton-master\Bin)

2. Include in the project you will work on, a REFERENCE to next DLL:

ComponentFactory.Krypton.Design.dll

Otherwise it won't draw controls in the form, but will place them in the foot of form designer.

I hope this can be of help.
