### ISSUE TITLE
KryptonTreeView: DoubleClick event does nothing

### ISSUE THREAD

**Issue by gordon-matt** [ComponentFactory/Krypton#35]
After changing a regular TreeView to a KryptonTreeView, the double click event no longer works. The event handler is still assigned correctly:

```
this.uiNavigatorTreeView.DoubleClick += new System.EventHandler(this.uiNavigatorTreeView_DoubleClick);
private void uiNavigatorTreeView_DoubleClick(object sender, EventArgs e)
        {
            OpenSelectedItem();
        }
```

**Comment by holgworknote** [comment]
Try this:
`
this.uiNavigatorTreeView.Controls[0].DoubleClick += new System.EventHandler(this.uiNavigatorTreeView_DoubleClick);
`

**Comment by gordon-matt** [comment]
That did the trick. Thanks
