### ISSUE TITLE
How do we recompile in Visual Studio

### ISSUE THREAD

**Issue by Wagnerp** [ComponentFactory/Krypton#39]
Hi,

I'm trying to convert the entire suite to use the .NET 4.7 Framework instead of the .NET 2.0 version. However I'm receiving errors in reference to the gacutil.exe -a command. Can anyone assist with this?

**Comment by ComponentFactory** [comment]
The gacutil command is run after the build succeeds in order to register the newly built controls into the GAC. If you remove and ignore this if you like.

**Comment by Wagnerp** [comment]
Ah ok, it maybe because I upgraded to the Creators Update SDK recently so I may have conflicts. I'll try removing the gacutil.exe bundled with the code to see if it resolves the issue.
