### ISSUE TITLE
All components in one library (dll)?

### ISSUE THREAD

**Issue by desarrollo03TR** [ComponentFactory/Krypton#44]
Is it possible?

**Comment by desarrollo03TR** [comment]
I have incluided all components (source) in one library/project, but the design project is not working fine, components only work if desing dll is added as reference.

**Comment by BlackBooth** [comment]
You could use a merger like [LibZ](https://github.com/MiloszKrajewski/LibZ). With that you can even merge all (managed) dlls into your executable.

**Comment by desarrollo03TR** [comment]
Thanks! I'll try it!

I guess my issue is design dll need to be added to GAC.

**Comment by desarrollo03TR** [comment]
Can you help me with Libz?

**Comment by BlackBooth** [comment]
Sure, please describe your desired configuration / result / way of deployment and I'll see what I can do.

**Comment by desarrollo03TR** [comment]
Thanks. What I need is to have only one dll with all the krypton components. Currently I have all the krypton components inside a library, and I can use ir but obviously I don't have designer support.

Can libz create a "Krypton.dll" library with all the krypton dll's inside with designer support?

thanks for the help.

**Comment by BlackBooth** [comment]
Hey @desarrollo03TR. Unfortunately I think that's not possible. I tried to merge the assemblies with LibZ and ILMerge but it didn't work. As far as I know, the Design.dll needs to be referenced separatly.

The way I do it is referencing all dlls separately and after compiling I merge all dlls into the executable with LibZ leaving me with only the exe.

**Comment by desarrollo03TR** [comment]
Thanks @BlackBooth , I think I can live with design as a separated library.
