### ISSUE TITLE
Button Text

### ISSUE THREAD

**Issue by Wagnerp** [ComponentFactory/Krypton#45]
Is there a way that we can change the KryptonButton font property?

**Comment by epje** [comment]
Hey @Wagnerp,
There is indeed a way of changing this. If you navigate to the Properties window for the button in question, and then go to: `StateCommon -> Content -> ShortText`, there should be a property called Font.

You can, of course, set different styles for the button when it's in different states, such as `StateDisabled` or `StatePressed`, for when the button is disabled and pressed respectively.

Hope this is what you're after!
~Ed

**Comment by Wagnerp** [comment]
Hi @epje,

Thanks for your help. It has driven me crazy finding the Font property, especially when enlarging controls!
