### ISSUE TITLE
Showing popups

### ISSUE THREAD

**Issue by desarrollo03TR** [ComponentFactory/Krypton#49]
Is there a easy way to show popups? for example, clicking a button and then show a popup with controls inside.

**Comment by holgworknote** [comment]
I found only one simple way to implement popup control panel with Krypton.

![krypton popup](https://cloud.githubusercontent.com/assets/20695413/26663965/72c8e7ea-469f-11e7-9015-d2105551ec8b.png)

**Comment by desarrollo03TR** [comment]
Thanks for the tip! (it is really useful) but I'm looking for floating popups, like a tooltip but with controls inside of the popup.

**Comment by desarrollo03TR** [comment]
At the end, I'm using the SimplePopup dll from here: https://www.codeproject.com/Articles/17502/Simple-Popup-Control

Thanks!
