### ISSUE TITLE
Is it possible to keep chrome enabled and prevent the custom style of the base palette?

### ISSUE THREAD

**Issue by bytedreamer** [ComponentFactory/Krypton#5]
We use the Office 2010 Palette for our Krypton controls. Moving forward, we want to use the standard windows frame. This can easily be done by disabling chrome, however the ribbon has extra space between it and the top of the window. I notice that the ribbon examples has standard window frames with chrome enabled. I couldn't figure out how it is done in the example. Any guidance would be appreciated.

**Comment by Cocotteseb** [comment]
Hi,

Please check if : 
On the form which contains the ribbon : AllowFormChrome = true
KryptonRibbon.AllowFormIntegrate = false if you are use the Krypton chrome from the palette, true if you are using the standard (glass) Windows chrome.

**Comment by bytedreamer** [comment]
That did the trick, thanks!

The Krypton Manager did prevent these settings from working properly. I would assume it override the chrome settings on the window.
