### ISSUE TITLE
Is there any way could change KryptonDateTimePicker Calendar font size?

### ISSUE THREAD

**Issue by huangjinshe** [ComponentFactory/Krypton#8]
When I click `KryptonDateTimePicker`  There is a Calendar will show up. Because I'm using a smaller font size for all application, It look like very small. 

So Is there anyway could change only the Calendar font size?  Thanks.

**Comment by huangjinshe** [comment]
As you see in the picture, the week name not show. and there is too small space between those days.

Or some option for change the space between those label.

![001](https://cloud.githubusercontent.com/assets/3822799/18806548/0fa883c4-8263-11e6-9b20-5fd0cf3143f6.png)

**Comment by huangjinshe** [comment]
@ComponentFactory , Could you give me some advice?

**Comment by iradicus** [comment]
If you use a custom palette (**KryptonPalette** component), you can set the calendar font.

`Palette1.CalendarDay.StateCommon.Content.ShortText.Font = New Font("Arial", 15);`

**Comment by huangjinshe** [comment]
@iradicus , Thank you but not working, maybe that's because I'm using custom palette:

```
internal sealed class PaletteBlue : PaletteOffice2010Blue
    {
        private static PaletteBlue self;
        internal System.Drawing.Font currentResourceFont = new System.Drawing.Font(Resources.GetRes().GetString("FontName"), float.Parse(Resources.GetRes().GetString("FontSize")));

        public static PaletteBlue GetSelf()
        {
            if (null == self)
                self = new PaletteBlue();
            return self;
        }

        

        private string fontName = Resources.GetRes().GetString("FontName");
        private float fontSize = float.Parse(Resources.GetRes().GetString("FontSize"));
        public override string BaseFontName
        {
            get
            {
                return this.fontName;
            }
            set
            {
                base.BaseFontName = value;
            }
        }

        public override float BaseFontSize
        {
            get
            {
                return fontSize;
            }
            set
            {
                base.BaseFontSize = value;
            }
        }
}
```

I did it for a global font and font size, but I don't know how I could ignore the calendar font size in it.

**Comment by huangjinshe** [comment]
I'm using `宋体` 9f.  and the problem will come. Other font no this problem.

**Comment by iradicus** [comment]
You could just add this.
```
public override System.Drawing.Font GetContentShortTextFont(PaletteContentStyle style, PaletteState state)
{
	if (style == PaletteContentStyle.ButtonCalendarDay)
		return new System.Drawing.Font("Arial", 15);
	else
		return base.GetContentShortTextFont(style, state);
}
```

**Comment by huangjinshe** [comment]
@iradicus , It worked. Thank you so much.

**Comment by huangjinshe** [comment]
The month not display, but the font size more bigger now.
