### ISSUE TITLE
KryptonLinkLabel is completely useless ?

### ISSUE THREAD

**Issue by omarrrio** [ComponentFactory/Krypton#93]
So how does it work ? isn't it supposed to let's say "link" to something, where do i put the link ? there is no Links.add method nor is there LinkData at all, somehow it's worst than a normal stock label.

**Comment by fire-eggs** [comment]
Quoting from the documentation:

> Use the KryptonLinkLabel control when you need to display a hyper link in conjunction with the styling features of the Krypton Toolkit. This control allows the user to initiate an action by pressing the hyper link in order to generate a LinkClicked event. The content of the control is contained in the Values property. You can define Text, ExtraText and Image details within the Values property.

...
>There are three options for deciding if the hyper link should be underlined. The default value of the LinkBehavior property is AlwaysUnderline and so the hyper link has an underline at all times. If you prefer to have an underline only when the mouse is hovering over the hyper link then change the property to HoverUnderline. Finally the NeverUnderline is appropriate when you never want the text underlined.

Based on the examples, it appears your 'link' behavior is to be implemented in the 'LinkClicked' event.

What you're getting from this control instead of a stock label is:
1. Underlining
2. Browser-style 'visited' behavior
3. An 'on-click' event.

**Comment by omarrrio** [comment]
Ah, thank you for the clarification.
